name:                KWIC
version:             0.1.0.0
github:              "LayrNeto/key-word-in-context"
license:             BSD-3-Clause
author:              "Layr de Andrade Neto"
maintainer:          "netolayr@gmail.com"
copyright:           "2025 Layr de Andrade Neto"

extra-source-files:
- README.md
- CHANGELOG.md
- data/stop_words.txt
- static/index.html
- static/reset.css
- static/style.css

# Metadata used when publishing your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

synopsis:            A web-based KWIC application written in Haskell.
category:            Web

description:         A Haskell implementation of Key Word in Context (KWIC) with a web interface.

dependencies:
- base >= 4.7 && < 5
- hspec
- containers
- mtl
- scotty
- text
- wai-extra
- wai-middleware-static
- aeson
- bytestring
- http-types
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - KWIC
  dependencies:
    - base
    - containers
    - mtl

executables:
  KWIC-web:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KWIC
    - base

tests:
  KWIC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KWIC
    - hspec
    - base
